# Generated by Django 4.2.3 on 2023-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(default='certificates/default.pdf', upload_to='certificates/'),
        ),
    ]
