# Generated by Django 4.2.3 on 2023-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_certificatetemplate_alter_certificate_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='template_file',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='html_content',
            field=models.TextField(default='<div>Your default certificate template</div>'),
        ),
    ]
