# Generated by Django 4.2.3 on 2023-07-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0004_remove_certificatetemplate_template_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='html_content',
            field=models.TextField(),
        ),
    ]
